version: '3.8'

services:
  web:
    build: .
    ports:
      - "8889:8889"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mysql+pymysql://root:${{secrets.MYSQL_PASSWORD}}@${{ secrets.MYSQL_HOST }}:3306/${{secrets.MYSQL_DB}}
    depends_on:
      - anecode-db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  anecode-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '${{secrets.SSH_PASSWORD}}'
      MYSQL_DATABASE: '${{secrets.MYSQL_DB}}'
      MYSQL_USER: root
      MYSQL_PASSWORD: '${{secrets.MYSQL_PASSWORD}}'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:/var/lib/mysql