  version: "3.9"
  services:
    frontend:
      build: .
      volumes:
      - .:/app
      image: ghcr.io/whaleopop/anecode-app:latest
      container_name: anecode-frontend
      ports:
        - "8080:8080"
      restart: always
      environment:
      - NODE_ENV=production