name: Deploy Vue 3 + Vite App with Docker

on:
  push:
    branches:
      - frontend

env:
  IMAGE_NAME: ghcr.io/whaleopop/anecode-frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Keys and known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add host to known_hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Debug SSH Setup
        run: |
          ls -la ~/.ssh
          cat ~/.ssh/id_rsa || echo "SSH private key is invalid or missing"

      - name: Start ssh-agent and add SSH key
        run: |
          eval $(ssh-agent -s)
          ssh-add -v ~/.ssh/id_rsa

      - name: Install OpenSSH Client and sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client sshpass

      - name: Execute remote commands with sshpass to create deploy user and group
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} << 'EOF'
          if ! id -u deploy_user &>/dev/null; then
            useradd -m deploy_user
            echo "deploy_user:password" | chpasswd
            groupadd docker  # Ensure docker group exists
            usermod -aG docker deploy_user
          fi
          EOF

      - name: Stop and delete existing Docker container
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} << 'EOF'
          if docker ps -a --format '{{.Names}}' | grep -Eq '^anecode-frontend$'; then
            docker stop anecode-frontend && docker rm anecode-frontend
          fi
          EOF


      - name: Pull and deploy new Docker container
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} << 'EOF'
          docker pull ghcr.io/whaleopop/anecode-frontend:latest
          docker run -d --name anecode-frontend -p 8080:80 ghcr.io/whaleopop/anecode-frontend:latest 
          EOF